# MariaDB configuration
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/cheap
    username: cheap_user
    password: ${DB_PASSWORD:changeme}
    driver-class-name: org.mariadb.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schemas/mariadb/mariadb-cheap.sql

cheap:
  database:
    type: mariadb
