# SQLite configuration
spring:
  datasource:
    url: jdbc:sqlite:${CHEAP_DB_PATH:./cheap.db}
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schemas/sqlite/sqlite-cheap.sql

cheap:
  database:
    type: sqlite
