spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

cheap:
  database:
    type: postgres
  pagination:
    default-page-size: 20
    max-page-size: 100
  aspect-upsert:
    max-batch-size: 10

logging:
  level:
    net.netbeing.cheap: DEBUG
    org.springframework: INFO
    io.zonky.test.db.postgres: INFO
